using Newtonsoft.Json;
using System;

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace ibtSessionLibrary.Info
{
    public class Driver
    {
        [JsonProperty("CarIdx")]
        public string CarIdx { get; set; }

        [JsonProperty("UserName")]
        public string UserName { get; set; }

        [JsonProperty("AbbrevName")]
        public object AbbrevName { get; set; }

        [JsonProperty("Initials")]
        public object Initials { get; set; }

        [JsonProperty("UserID")]
        public string UserID { get; set; }

        [JsonProperty("TeamID")]
        public string TeamID { get; set; }

        [JsonProperty("TeamName")]
        public string TeamName { get; set; }

        [JsonProperty("CarNumber")]
        public string CarNumber { get; set; }

        [JsonProperty("CarNumberRaw")]
        public string CarNumberRaw { get; set; }

        [JsonProperty("CarPath")]
        public string CarPath { get; set; }

        [JsonProperty("CarClassID")]
        public string CarClassID { get; set; }

        [JsonProperty("CarID")]
        public string CarID { get; set; }

        [JsonProperty("CarIsPaceCar")]
        public string CarIsPaceCar { get; set; }

        [JsonProperty("CarIsAI")]
        public string CarIsAI { get; set; }

        [JsonProperty("CarScreenName")]
        public string CarScreenName { get; set; }

        [JsonProperty("CarScreenNameShort")]
        public string CarScreenNameShort { get; set; }

        [JsonProperty("CarClassShortName")]
        public string CarClassShortName { get; set; }

        [JsonProperty("CarClassRelSpeed")]
        public string CarClassRelSpeed { get; set; }

        [JsonProperty("CarClassLicenseLevel")]
        public string CarClassLicenseLevel { get; set; }

        [JsonProperty("CarClassMaxFuelPct")]
        public string CarClassMaxFuelPct { get; set; }

        [JsonProperty("CarClassWeightPenalty")]
        public string CarClassWeightPenalty { get; set; }

        [JsonProperty("CarClassColor")]
        public string CarClassColor { get; set; }

        [JsonProperty("IRating")]
        public string IRating { get; set; }

        [JsonProperty("LicLevel")]
        public string LicLevel { get; set; }

        [JsonProperty("LicSubLevel")]
        public string LicSubLevel { get; set; }

        [JsonProperty("LicString")]
        public string LicString { get; set; }

        [JsonProperty("LicColor")]
        public string LicColor { get; set; }

        [JsonProperty("IsSpectator")]
        public string IsSpectator { get; set; }

        [JsonProperty("CarDesignStr")]
        public string CarDesignStr { get; set; }

        [JsonProperty("HelmetDesignStr")]
        public string HelmetDesignStr { get; set; }

        [JsonProperty("SuitDesignStr")]
        public string SuitDesignStr { get; set; }

        [JsonProperty("CarNumberDesignStr")]
        public string CarNumberDesignStr { get; set; }

        [JsonProperty("CarSponsor_1")]
        public string CarSponsor1 { get; set; }

        [JsonProperty("CarSponsor_2")]
        public string CarSponsor2 { get; set; }
    }

    public class DriverInfo
    {
        [JsonProperty("DriverCarIdx")]
        public string DriverCarIdx { get; set; }

        [JsonProperty("PaceCarIdx")]
        public string PaceCarIdx { get; set; }

        [JsonProperty("DriverHeadPosX")]
        public string DriverHeadPosX { get; set; }

        [JsonProperty("DriverHeadPosY")]
        public string DriverHeadPosY { get; set; }

        [JsonProperty("DriverHeadPosZ")]
        public string DriverHeadPosZ { get; set; }

        [JsonProperty("DriverCarIdleRPM")]
        public string DriverCarIdleRPM { get; set; }

        [JsonProperty("DriverCarRedLine")]
        public string DriverCarRedLine { get; set; }

        [JsonProperty("DriverCarFuelKgPerLtr")]
        public string DriverCarFuelKgPerLtr { get; set; }

        [JsonProperty("DriverCarFuelMaxLtr")]
        public string DriverCarFuelMaxLtr { get; set; }

        [JsonProperty("DriverCarMaxFuelPct")]
        public string DriverCarMaxFuelPct { get; set; }

        [JsonProperty("DriverCarSLFirstRPM")]
        public string DriverCarSLFirstRPM { get; set; }

        [JsonProperty("DriverCarSLShiftRPM")]
        public string DriverCarSLShiftRPM { get; set; }

        [JsonProperty("DriverCarSLLastRPM")]
        public string DriverCarSLLastRPM { get; set; }

        [JsonProperty("DriverCarSLBlinkRPM")]
        public string DriverCarSLBlinkRPM { get; set; }

        [JsonProperty("DriverPitTrkPct")]
        public string DriverPitTrkPct { get; set; }

        [JsonProperty("DriverCarEstLapTime")]
        public string DriverCarEstLapTime { get; set; }

        [JsonProperty("DriverSetupName")]
        public string DriverSetupName { get; set; }

        [JsonProperty("DriverSetupIsModified")]
        public string DriverSetupIsModified { get; set; }

        [JsonProperty("DriverSetupLoadTypeName")]
        public string DriverSetupLoadTypeName { get; set; }

        [JsonProperty("DriverSetupPassedTech")]
        public string DriverSetupPassedTech { get; set; }

        [JsonProperty("Drivers")]
        public Driver[] Drivers { get; set; }

        public Driver CurrentDriver()
        {
            return Drivers[Convert.ToInt32(DriverCarIdx)];
        }
    }
}
