using Newtonsoft.Json;

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace iRacing.TelemetryParser.Session.Info
{
    public class Session
    {
        [JsonProperty("SessionNum")]
        public string SessionNum { get; set; }

        [JsonProperty("SessionLaps")]
        public string SessionLaps { get; set; }

        [JsonProperty("SessionTime")]
        public string SessionTime { get; set; }

        [JsonProperty("SessionNumLapsToAvg")]
        public string SessionNumLapsToAvg { get; set; }

        [JsonProperty("SessionType")]
        public string SessionType { get; set; }

        [JsonProperty("SessionTrackRubberState")]
        public string SessionTrackRubberState { get; set; }

        [JsonProperty("ResultsPositions")]
        public object ResultsPositions { get; set; }

        [JsonProperty("ResultsFastestLap")]
        public ResultsFastestLap[] ResultsFastestLap { get; set; }

        [JsonProperty("ResultsAverageLapTime")]
        public string ResultsAverageLapTime { get; set; }

        [JsonProperty("ResultsNumCautionFlags")]
        public string ResultsNumCautionFlags { get; set; }

        [JsonProperty("ResultsNumCautionLaps")]
        public string ResultsNumCautionLaps { get; set; }

        [JsonProperty("ResultsNumLeadChanges")]
        public string ResultsNumLeadChanges { get; set; }

        [JsonProperty("ResultsLapsComplete")]
        public string ResultsLapsComplete { get; set; }

        [JsonProperty("ResultsOfficial")]
        public string ResultsOfficial { get; set; }
    }

    public class SessionInfo
    {

        [JsonProperty("Sessions")]
        public Session[] Sessions { get; set; }
    }


    public class ResultsFastestLap
    {

        [JsonProperty("CarIdx")]
        public string CarIdx { get; set; }

        [JsonProperty("FastestLap")]
        public string FastestLap { get; set; }

        [JsonProperty("FastestTime")]
        public string FastestTime { get; set; }
    }
}
