using Newtonsoft.Json;

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace ibtParserLibrary.Session.Info
{
    public class Sector
    {

        [JsonProperty("SectorNum")]
        public string SectorNum { get; set; }

        [JsonProperty("SectorStartPct")]
        public string SectorStartPct { get; set; }
    }

    public class SplitTimeInfo
    {

        [JsonProperty("Sectors")]
        public Sector[] Sectors { get; set; }
    }
}
