using iRacing.TelemetryParser.Session.Info;
using Newtonsoft.Json;

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace iRacing.TelemetryParser.Session
{
    public class TelemetrySessionInfo : ITelemetrySessionInfo
    {
        [JsonProperty("WeekendInfo")]
        public WeekendInfo WeekendInfo { get; set; }

        [JsonProperty("SessionInfo")]
        public SessionInfo SessionInfo { get; set; }

        [JsonProperty("CameraInfo")]
        public CameraInfo CameraInfo { get; set; }

        [JsonProperty("DriverInfo")]
        public DriverInfo DriverInfo { get; set; }

        [JsonProperty("RadioInfo")]
        public RadioInfo RadioInfo { get; set; }     

        [JsonProperty("SplitTimeInfo")]
        public SplitTimeInfo SplitTimeInfo { get; set; }   

        [JsonIgnore()]
        public string SetupJSON { get; set; }  
    }
}
